services:
  postgres:
    image: postgres:13.4-alpine
    container_name: password-manager-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: password-manager
    ports:
      - "45432:5432"
  redis:
    image: redis:7.0
    container_name: password-manager-redis
    restart: always
    ports:
      - "36379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  elastic:
    image: elasticsearch:7.17.9
    container_name: demo-elastic
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: demo-kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://demo-elastic:9200
    depends_on:
      - elastic
