spring:
  datasource:
    url: jdbc:postgresql://localhost:45432/password-manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 36379
elastic:
  url: localhost:9200